name: SimpleJumpPad
version: @version@
main: me.nutyworks.simplejumppad.SimpleJumpPadPlugin
api-version: '1.13'
authors: [nutyworks]
commands:
  togglejumppad:
    aliases: [tjp]
    description: Toggles jump pad place mode.
    usage: /<command>
